require(shinyLikert)
require(likert)
td = likert::likert( testData2$likert_data )
class(td)
likert.bar.plot(td)
likert.heat.plot(td)
td = likert::likert( testData2$likert_data, grouping = testData2$row_factors[,2] )
likert.bar.plot(td, include.histogram = TRUE )
HH::likert( td )
likert.bar.plot( td )
