---
title: "Reactive Inputs"
author: "Gregor de Cillia"
output: html_document
runtime: shiny
---


```{r, chunk1, eval = FALSE }
textInput( "main", "main", "my main" )
checkboxInput( "horizontal", "horizontal" )
library( shinyLikert )

plot(
  renderShinyLikert( createTestData(),
                     main =  reactive({input$main}),
                     horizontal = reactive({input$horizontal}),
                     as.percent = TRUE )
)
```

```{r, ref.label='chunk1', echo=FALSE}

```

```{r, chunk2, eval = FALSE }
textInput( "main2", "main2", "my main" )
checkboxInput( "as.percent", "as.percent" )

plot(
  renderShinyLikert( createTestData(),
                     main =  reactive({input$main2}),
                     as.percent = reactive({input$as.percent}),
                     split = "gender" )
)
```

```{r, ref.label='chunk2', echo=FALSE}

```

```{r, chunk3, eval=FALSE}
sliderInput("center","center",1.5,4.5,3,0.5)
plot(
  renderShinyLikert( createTestData(),
                     dropdown = "difficulty",
                     center = reactive({input$center}),
                     group = "gender" )
)
```

```{r, ref.label='chunk3', echo=FALSE}

```

```{r, chunk4, eval = FALSE }
checkboxInput("as.percent2","as.percent2")
plot( renderShinyLikert( createTestData(),
                         dropdown = "difficulty",
                         as.percent = reactive({
                           input$as.percent2}),
                         group = "gender",
                         grouping = "HH" )
      )
```

```{r, ref.label='chunk4', echo=FALSE}

```
