---
title: "Examples"
author: "Gregor de Cillia"
output: 
  html_document: 
    highlight: textmate
    theme: united
    toc: yes
runtime: shiny
---

```{r, results='hide', message=FALSE}
  library( shinyLikert )
  #data( cartell )
  load( "../../data_nobuild/cartell.rda")
```


```{r, eval = FALSE, echo=FALSE, results='hide'}
 data <- read.delim("C:/Users/grogon/Downloads/data.csv")
 source( "C:/Users/grogon/workspace/shinyLikert/examples/cartell_questions.R" )
 question_columns = 1:163
 factor_columns   = c( "age", "gender", "country", "source" ) 
 
 question_factors = substr( names( data[,question_columns] ), 1, 1)
 
 library( shinyLikert )
 #
 ld = createLikertData( data[ , question_columns ],
                        data[ , factor_columns ],
                        data.frame(  question_type = question_factors ),
                        c( "missed",
                           "strongly disagree", 
                           "disagree", 
                           "neither agree not disagree", 
                           "agree", 
                           "strongly agree" )
                   )

 question_factors = substr( names( ld$likert_data ), 1, 1)
 names(ld$likert_data) = cartell_questions
 
 
 
 
 levels( ld$row_factors$country ) = c( levels( ld$row_factors$country ), 
                                       "unanswered" )
 ld$row_factors$country[ is.na( ld$row_factors$country ) ] = "unanswered"
 levels( ld$row_factors$gender ) = c( "NA",
                                      "Male",
                                      "Female",
                                      "Other"
                                      )
 
 c( "from front page of website that hosted the survey",
    "from google",
    "facebook",
    "any url containing '.edu'",
    "wikipedia",
    "other source or empty source")

```

```{r}
 # summary( cartell_data )
 cartell_data$input  = input
 cartell_data$output = output
 fluidPage(
   renderFactorOverview( cartell_data )
 )
 
 cartell_data$column_factors = cbind( cartell_data$column_factors,
                                      question = names(cartell_data$likert_data)
  )
 cartell_data$likert_data  = cartell_data$likert_data[1:2000,]
 cartell_data$row_factors  = cartell_data$row_factors[1:2000,]

  rendered2 = renderShinyLikert(
        cartell_data , 
        dropdown = c("question" ),
        split = c("source","gender"),
        response_levels = c( #"missed",
                             "strongly disagree", 
                             "disagree", 
                             "neither agree not disagree", 
                             "agree", 
                             "strongly agree" ),
        as.percent = TRUE,
        positive.order = TRUE
  )
  rendered2$selector
  rendered2$plot 
 
```

```{r}
  # replace missing answers with NAs
  i = 1
  for( question in cartell_data$likert_data ){
    question[question == "missed"] = NA
    cartell_data$likert_data[,i] = factor( question )
    i = i + 1
  }

  fluidPage(
  renderShinyLikert(
        cartell_data,
        dropdown = c("question_type" ),
        group = "gender",
        as.percent = TRUE,
        height = c(750,1500)
  )
  )
```
