---
title: "Cattell's 16 Personality Factors Test"
author: "Gregor de Cillia"
output: 
  html_document: 
    highlight: textmate
    theme: united
    toc: yes
runtime: shiny
---

```{r, results='hide', message=FALSE}
  library( shinyLikert )
  load( "cattell_data.rda")
```


```{r, eval = FALSE, echo=FALSE, results='hide'}
 data <- read.delim("C:/Users/grogon/Downloads/data.csv")
 source( "C:/Users/grogon/workspace/shinyLikert/examples/cartell_questions.R" )
 question_columns = 1:163
 factor_columns   = c( "age", "gender", "country", "source" ) 
 
 question_factors = substr( names( data[,question_columns] ), 1, 1)
 
 library( shinyLikert )
 #
 ld = createLikertData( data[ , question_columns ],
                        data[ , factor_columns ],
                        data.frame(  question_type = question_factors ),
                        c( "missed",
                           "strongly disagree", 
                           "disagree", 
                           "neither agree not disagree", 
                           "agree", 
                           "strongly agree" )
                   )

 question_factors = substr( names( ld$likert_data ), 1, 1)
 names(ld$likert_data) = cartell_questions
 
 
 
 
 levels( ld$row_factors$country ) = c( levels( ld$row_factors$country ), 
                                       "unanswered" )
 ld$row_factors$country[ is.na( ld$row_factors$country ) ] = "unanswered"
 levels( ld$row_factors$gender ) = c( "NA",
                                      "Male",
                                      "Female",
                                      "Other"
                                      )
 
 c( "from front page of website that hosted the survey",
    "from google",
    "facebook",
    "any url containing '.edu'",
    "wikipedia",
    "other source or empty source")

```

```{r}
 # skip summary since the calculation of the likert response count
 # takes some time.
 #summary( cattell_data )
 
 # supply input and output to the dataset to enable interaction of
 # all functions which take cattell_data as input.
 cattell_data$input  = input
 cattell_data$output = output
 
 # display the fator overview
 fluidPage(
   renderFactorOverview( cattell_data )
 )
 
 # add question as column_factor. This way, questions can be selected
 # through a dropdown input
 cattell_data$column_factors = cbind( 
   cattell_data$column_factors,
   question = names(cattell_data$likert_data)
  )
 
 # remove some entries to speed up the server tasks. Note, that this
 # dataset had 49159 participants
 cattell_data$likert_data  = cattell_data$likert_data[1:2000,]
 cattell_data$row_factors  = cattell_data$row_factors[1:2000,]

 rendered2 = renderShinyLikert(
   cattell_data , 
   dropdown = c( "question_type", "question" ),
   split = c( "source", "gender" ),
   response_levels = c( 
     #"missed",                      # do not plot the missings
                                     # this can be avoided by replacing
                                     # missed with NAs in likert_data
     "strongly disagree", 
     "disagree", 
     "neither agree not disagree", 
     "agree", 
     "strongly agree" ),
   as.percent = TRUE
 )
 rendered2$selector
 rendered2$plot 
 
```

```{r}
 # replace missing answers with NAs
 i = 1
 for( question in cattell_data$likert_data ){
   question[question == "missed"] = NA
   cattell_data$likert_data[,i] = factor( question )
   i = i + 1
 }

 # Call renderShinyLikert and plot the result
 plot(
   renderShinyLikert(
     cattell_data,
     dropdown = c( "question_type" ),
     group = "gender",
     as.percent = TRUE,
     height = c(750,1500)
   )
 )
```
