cattell_questions = c(
  # A
  "I know how to comfort others",
  "I enjoy bringing people together",
  "I feel others' emotions",
  "I take an interest in other people's lives",
  "I cheer people up",
  "I make people feel at ease",
  "I take time out for others",
  "I don't like to get involved in other people's problems",
  "I am not really interested in others",
  "I try not to think about the needy",
  # B
  "I make insightful remarks",
  "I know the answers to many questions",
  "I tend to analyze things",
  "I use my brain",
  "I learn quickly",
  "I counter others' arguments",
  "I reflect on things before acting",
  "I weigh the pros against the cons",
  "I consider myself an average person",
  "I get confused easily",
  "I know that I am not a special person",
  "I have a poor vocabulary",
  "I skip difficult words while reading",
  # C
  "I seldom feel blue",
  "I feel comfortable with myself",
  "I readily overcome setbacks",
  "I am relaxed most of the time",
  "I am not easily frustrated",
  "I have frequent mood swings",
  "I often feel blue",
  "I dislike myself",
  "I feel desperate",
  "I am easily discouraged",
  # D
  "I take charge",
  "I want to be in charge",
  "I say what I think",
  "I am not afraid of providing criticism",
  "I take control of things",
  "I can take strong measures",
  "I wait for others to lead the way",
  "I never challenge things",
  "I let others make the decisions",
  "I let myself be pushed around",
  # E
  "I am the life of the party",
  "I love large parties",
  "I joke around a lot",
  "I enjoy being part of a loud crowd",
  "I amuse my friends",
  "I act wild and crazy",
  "I seldom joke around",
  "I don't like crowded events",
  "I am the last to laugh at a joke",
  "I dislike loud music",
  # F
  "I believe laws should be strictly enforced",
  "I try to follow the rules",
  "I believe in one true religion",
  "I respect authority",
  "I like to stand during the national anthem",
  "I resist authority",
  "I break rules",
  "I use swear words",
  "I oppose authority",
  "I know how to get around the rules",
  # G
  "I feel comfortable around people",
  "I talk to a lot of different people at parties",
  "I don't mind being the center of attention",
  "I make friends easily",
  "I start conversations",
  "I find it difficult to approach others",
  "I often feel uncomfortable around others",
  "I have little to say",
  "I am quiet around strangers",
  "I keep in the background",
  # H
  "I like to read",
  "I enjoy discussing movies and books with others",
  "I read a lot",
  "I don't like action movies",
  "I cry during movies",
  "I love flowers",
  "I do not enjoy watching dance performances",
  "I do not like poetry",
  "I dislike works of fiction",
  "I rarely notice my emotional reactions",
  # I
  "I find it hard to forgive others",
  "I suspect hidden motives in others",
  "I am wary of others",
  "I distrust people",
  "I believe that people seldom tell you the whole truth",
  "I believe that people are essentially evil",
  "I trust what people say",
  "I trust others",
  "I believe that others have good intentions",
  "I believe that people are basically moral",
  # J
  "I do things that others find strange",
  "I like to get lost in thought",
  "I enjoy wild flights of fantasy",
  "I love to daydream",
  "I swim against the current",
  "I take deviant positions",
  "I do unexpected things",
  "I do things by the book",
  "I seldom daydream",
  "I seldom get lost in thought",
  # K
  "I reveal little about myself",
  "I am hard to get to know",
  "I don't talk a lot",
  "I bottle up my feelings",
  "I keep my thoughts to myself",
  "I am open about myself to others",
  "I am open about my feelings",
  "I disclose my intimate thoughts",
  "I show my feelings",
  "I am willing to talk about myself",
  # L
  "I am afraid that I will do the wrong thing",
  "I feel threatened easily",
  "I am easily hurt",
  "I worry about things",
  "I spend time thinking about past mistakes",
  "I feel guilty when I say 'no'",
  "I feel crushed by setbacks",
  "I don't worry about things that have already happened",
  "I am not easily bothered by things",
  "I don't let others discourage me",
  # M
  "I believe in the importance of art",
  "I love to think up new ways of doing things",
  "I enjoy hearing new ideas",
  "I carry the conversation to a higher level",
  "I prefer variety to routine",
  "I avoid philosophical discussions",
  "I rarely look for a deeper meaning in things",
  "I am not interested in theoretical discussions",
  "I am not interested in abstract ideas",
  "I try to avoid complex people",
  # N
  "I want to be left alone",
  "I prefer to do things by myself",
  "I enjoy spending time by myself",
  "I seek quiet",
  "I don't mind eating alone",
  "I enjoy silence",
  "I enjoy my privacy",
  "I enjoy being part of a group",
  "I enjoy teamwork",
  "I can't do without the company of others",
  # O
  "I want everything to be 'just right'",
  "I get chores done right away",
  "I like order",
  "I continue until everything is perfect",
  "I am exacting in my work",
  "I am not bothered by messy people",
  "I am not bothered by disorder",
  "I leave a mess in my room",
  "I leave my belongings around",
  "I put off unpleasant tasks",
  # P
  "I get irritated easily",
  "I get angry easily",
  "I am quick to judge others",
  "I am annoyed by others' mistakes",
  "I am easily put out",
  "I can't stand being contradicted",
  "I judge people by their appearance",
  "I am not easily annoyed",
  "I try to forgive and forget",
  "P 10"
)
